#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
Production-Ready Telegram Gateway Bot
Generated by: Telegram Bot & Campaign Generator

This bot acts as a membership-verification gateway. When users access the bot using 
deep links (e.g., t.me/YourBot?start=campaign_name), they are prompted to join a 
required Telegram channel. Only after joining will they receive their destination link.

Requirements:
- Python 3.8+
- python-telegram-bot >= 20.0
- python-dotenv

Deployment:
- Install dependencies: pip install -r requirements.txt
- Create .env with your BOT_TOKEN
- Make sure this bot is added as an ADMINISTRATOR in your required channels.
"""

import os
import json
import logging
from typing import Dict, Any, Optional
from dotenv import load_dotenv
from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup
from telegram.ext import (
    ApplicationBuilder,
    CommandHandler,
    ContextTypes,
    CallbackQueryHandler,
    Defaults,
)
from telegram.constants import ParseMode

# Load environment variables
load_dotenv()

# Configure Logging
logging.basicConfig(
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    level=logging.INFO
)
logger = logging.getLogger(__name__)

# Check for Bot Token
BOT_TOKEN = os.getenv("BOT_TOKEN")
if not BOT_TOKEN:
    logger.critical("CRITICAL ERROR: BOT_TOKEN is missing in .env file!")
    raise ValueError("BOT_TOKEN environment variable is not set. Please check your .env file.")

# Path to campaigns configuration
CONFIG_PATH = os.path.join(os.path.dirname(__file__), "config.json")

def load_gateway_config() -> Dict[str, Any]:
    """
    Loads gateway campaign settings from config.json.
    Refreshes dynamically on file edit without needing to restart the bot.
    """
    try:
        if os.path.exists(CONFIG_PATH):
            with open(CONFIG_PATH, "r", encoding="utf-8") as f:
                return json.load(f)
        else:
            logger.warning(f"Configuration file '{CONFIG_PATH}' not found. Using fallback defaults.")
    except Exception as e:
        logger.error(f"Failed to parse config.json: {e}")
    
    # Return default config skeleton if loading fails
    return {
        "fallback_welcome_message": "👋 Welcome! To access your requested link, you must first join our required channel.",
        "fallback_join_first_message": "❌ Access Denied! You are not a member of the required channel yet.\n\nPlease join the channel below, then click \"Verified & Try Again\".",
        "fallback_success_message": "✅ Verification Successful! Thank you for joining. Here is your link:",
        "campaigns": {}
    }


async def check_membership(context: ContextTypes.DEFAULT_TYPE, user_id: int, channel_username: str) -> bool:
    """
    Queries the Telegram API to verify if the user is a member of the required channel.
    IMPORTANT: The bot MUST be an administrator in the targeted channel for this to work!
    """
    # Clean username if needed
    if not channel_username.startswith("@"):
        channel_username = f"@{channel_username}"
        
    try:
        member = await context.bot.get_chat_member(chat_id=channel_username, user_id=user_id)
        # Acceptable states for being in a channel
        joined_statuses = ["creator", "administrator", "member"]
        if member.status in joined_statuses:
            logger.info(f"User {user_id} verified in channel {channel_username} (Status: {member.status})")
            return True
        logger.info(f"User {user_id} checked but NOT in channel {channel_username} (Status: {member.status})")
        return False
    except Exception as e:
        # Most common error: Bot is not an admin in the channel, or channel username is invalid
        logger.error(f"Error checking membership for user {user_id} in {channel_username}: {e}")
        logger.error("👉 RECOMMENDATION: Please ensure the bot is added as an ADMINISTRATOR in the channel with 'Invite Users' or 'Manage Chat' permissions!")
        # We default to False when checking fails to protect the gateway
        return False


async def start(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """
    Handles the /start command.
    Checks for deep link campaign parameters (e.g., /start naruto).
    """
    user = update.effective_user
    if not user:
        return

    # Check if a deep link parameter was passed (context.args contains arguments passed with command)
    campaign_key = context.args[0].lower().strip() if context.args else None
    
    config = load_gateway_config()
    campaigns = config.get("campaigns", {})

    # If no campaign or invalid campaign, show fallback / help info
    if not campaign_key or campaign_key not in campaigns:
        welcome_help = (
            f"<b>Hello {user.first_name}!</b>\n\n"
            "This bot is a gatekeeper for secure campaign links.\n"
            "To access links, use a valid deep link. E.g.:\n"
        )
        if campaigns:
            first_camp = list(campaigns.keys())[0]
            welcome_help += f"👉 <code>t.me/{context.bot.username}?start={first_camp}</code>\n\n"
            welcome_help += "<b>Available campaigns in config:</b>\n"
            for k in campaigns.keys():
                welcome_help += f"- <code>{k}</code>\n"
        else:
            welcome_help += "No campaigns are configured on this bot currently.\n"
            
        await update.message.reply_text(welcome_help, parse_mode=ParseMode.HTML)
        return

    campaign = campaigns[campaign_key]
    channel_username = campaign.get("channel_username")
    join_button_url = campaign.get("join_button_url") or f"https://t.me/{channel_username.replace('@', '')}"
    
    # Check if already a member
    is_member = await check_membership(context, user.id, channel_username)
    
    if is_member:
        # User is already a member - send direct link immediately!
        success_msg = campaign.get("success_message") or config.get("fallback_success_message")
        destination = campaign.get("destination_link")
        
        text = f"{success_msg}\n\n🔗 <a href='{destination}'><b>Click Here to Access</b></a>"
        await update.message.reply_text(text, parse_mode=ParseMode.HTML, disable_web_page_preview=True)
    else:
        # Prompt them to join
        welcome_msg = campaign.get("welcome_message") or config.get("fallback_welcome_message")
        
        # Build interactive buttons
        keyboard = [
            [InlineKeyboardButton("📢 Join Channel", url=join_button_url)],
            [InlineKeyboardButton("✅ Verified & Try Again", callback_data=f"verify_{campaign_key}")]
        ]
        reply_markup = InlineKeyboardMarkup(keyboard)
        
        await update.message.reply_text(
            welcome_msg,
            reply_markup=reply_markup,
            parse_mode=ParseMode.HTML
        )


async def button_handler(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """
    Handles inline keyboard callbacks (specifically the verification triggers).
    """
    query = update.callback_query
    await query.answer() # Acknowledge the callback immediately
    
    user_id = query.from_user.id
    data = query.data
    
    if not data or not data.startswith("verify_"):
        return
        
    campaign_key = data.replace("verify_", "")
    config = load_gateway_config()
    campaigns = config.get("campaigns", {})
    
    if campaign_key not in campaigns:
        await query.edit_message_text("⚠️ This campaign is no longer available.")
        return
        
    campaign = campaigns[campaign_key]
    channel_username = campaign.get("channel_username")
    join_button_url = campaign.get("join_button_url") or f"https://t.me/{channel_username.replace('@', '')}"
    
    # Double-check membership
    is_member = await check_membership(context, user_id, channel_username)
    
    if is_member:
        # Edit the message to show the destination link
        success_msg = campaign.get("success_message") or config.get("fallback_success_message")
        destination = campaign.get("destination_link")
        
        text = f"{success_msg}\n\n🔗 <a href='{destination}'><b>Click Here to Access</b></a>"
        await query.edit_message_text(text, parse_mode=ParseMode.HTML, disable_web_page_preview=True)
    else:
        # Warn user they haven't joined yet
        join_first_msg = campaign.get("join_first_message") or config.get("fallback_join_first_message")
        
        # We re-attach the keyboard so they can try again
        keyboard = [
            [InlineKeyboardButton("📢 Join Channel", url=join_button_url)],
            [InlineKeyboardButton("✅ Verified & Try Again", callback_data=f"verify_{campaign_key}")]
        ]
        reply_markup = InlineKeyboardMarkup(keyboard)
        
        # To avoid telegram raising "Message is not modified" error, we can check if content is different
        # or append an alert style/emoji variation
        import random
        emojis = ["🔒", "⛔", "⏳", "⚠️"]
        warning_text = f"{random.choice(emojis)} {join_first_msg}"
        
        try:
            await query.edit_message_text(
                warning_text,
                reply_markup=reply_markup,
                parse_mode=ParseMode.HTML
            )
        except Exception as e:
            # Silence message not modified error if clicked multiple times rapidly without joining
            if "Message is not modified" not in str(e):
                logger.error(f"Error updating query message: {e}")


def main() -> None:
    """
    Initializes and boots the telegram bot.
    """
    logger.info("Initializing bot setup...")
    
    # Configure global defaults like HTML parsing mode
    defaults = Defaults(parse_mode=ParseMode.HTML)
    
    # Build bot application
    application = ApplicationBuilder().token(BOT_TOKEN).defaults(defaults).build()
    
    # Attach command handlers
    application.add_handler(CommandHandler("start", start))
    
    # Attach inline callback handlers
    application.add_handler(CallbackQueryHandler(button_handler))
    
    # Start bot execution
    logger.info("🚀 Bot has successfully started! Press Ctrl+C to terminate.")
    application.run_polling()


if __name__ == "__main__":
    main()